/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2022-02-23 23:46:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CDC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LogonReg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1645658749917L));
    _jspx_dependants.put("jar:file:/C:/Users/eVmPr/Documents/IS240/JODEA_Project/VacTrackSys/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343837818000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Vac Track System - Member Login</title>\n");
      out.write("        <!--<link rel=\"stylesheet\" href=\"../Assets/Styles/main.css\" type=\"text/css\" />-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"../Assets/Styles/loginStyle.css\">\n");
      out.write("        <script src=\"../Assets/Scripts/validatescript.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"../Assets/Scripts/validatescript.js\" type=\"text/javascript\"></script>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body >\n");
      out.write("        <div class=\"hero\">\n");
      out.write("        <div class=\"form-box\">\n");
      out.write("            <div class=\"button-box\">\n");
      out.write("                <div id=\"btn\"></div>\n");
      out.write("                <button type=\"button\" class=\"toggle-btn\" onclick=\"login()\">Log In</button>\n");
      out.write("                <button type=\"button\" class=\"toggle-btn\" onclick=\"register()\">Register</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"social-icons\">\n");
      out.write("                <a href=\"https://www.mypatientchart.org/MyChart/Authentication/Login?\"> \n");
      out.write("                     <img src=\"../Assets/Images/download.png\">\n");
      out.write("                 </a> \n");
      out.write("                 <a href=\"https://physicians.wustl.edu/for-patients/mychart-patient-portal/\"> \n");
      out.write("                     <img src=\"../Assets/Images/washu2.png\">\n");
      out.write("                 </a>\n");
      out.write("                 <a href=\"https://www.mymercy.net/login\"> \n");
      out.write("                     <img src=\"../Assets/Images/mercy.jpg\">\n");
      out.write("                 </a>\n");
      out.write("            </div>\n");
      out.write("            <form id=\"login\" action=\"Login\"method=\"post\" class=\"input-group\">\n");
      out.write("                <input type=\"text\" class=\"input-field\" id=\"userid\" value=\"\" placeholder=\"User ID\" required>\n");
      out.write("                <input type=\"password\" class=\"input-field\" id=\"passwd\" value=\"\" placeholder=\"Enter Password\" required>\n");
      out.write("                <input type=\"checkbox\" class=\"check-box\"><span>Remember Password</span>\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\" onclick=\"ValidateL\n");
      out.write("                    ogin()\">Login</button>\n");
      out.write("            </form>\n");
      out.write("            <form id=\"register\" action=\"/NewAccount\" method=\"post\" class=\"input-group\" action=\"\">\n");
      out.write("                <input type=\"text\" class=\"input-field\" id=\"userid\" placeholder=\"User ID\" required>\n");
      out.write("                <input type=\"email\" class=\"input-field\" id=\"email\" placeholder=\"Email ID\" required>\n");
      out.write("                <input type=\"text\" class=\"input-field\" id=\"passwd\" placeholder=\"Enter Password\" required>\n");
      out.write("                <input type=\"text\" class=\"input-field\" id=\"confpasswd\" placeholder=\"Confirm Password\" required>\n");
      out.write("                <input type=\"checkbox\" class=\"check-box\"><span>I agree to the terms & conditions</span>\n");
      out.write("                <button type=\"submit\" id=\"newacct\" class=\"submit-btn\">Register</button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    var x = document.getElementById(\"login\");\n");
      out.write("    var y = document.getElementById(\"register\");\n");
      out.write("    var z = document.getElementById(\"btn\");\n");
      out.write("\n");
      out.write("    \n");
      out.write("    function register(){\n");
      out.write("        x.style.left = \"-400px\";\n");
      out.write("        y.style.left = \"50px\";\n");
      out.write("        z.style.left = \"110px\";\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function login(){\n");
      out.write("        x.style.left = \"50px\";\n");
      out.write("        y.style.left = \"450px\";\n");
      out.write("        z.style.left = \"0px\";\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
